Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def get_user(auth0_user):
  return database.get_user_by_id(auth0_user)

def delete_user_by_id(user_id):
  return database.delete_user(user_id)

auth0UserId = user['auth_0_user_id']

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[30], line 7[0m
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mdelete_user_by_id[39m(user_id):
[1;32m      5[0m   [38;5;28;01mreturn[39;00m database[38;5;241m.[39mdelete_user(user_id)
[0;32m----> 7[0m auth0UserId [38;5;241m=[39m [43muser[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mauth_0_user_id[39;49m[38;5;124;43m'[39;49m[43m][49m

[0;31mKeyError[0m: 'auth_0_user_id'

